### PR TITLE
2.1.0

### PR DESCRIPTION
**Pull request by esphen**
#### Featues
- #106 Adds request body presets
- #103 Default request body is now json
- #88 The user's previously selected body preset is now presisted across reloads for new requests
- #78 Changes the request body to be expanded by default
- #84 Adds support for viewing headers of server-initiated redirects 

#### Fixes
- #104 Fixes most headers not being visible on Chrome due to CORS
- #75 Ensures the `Content-Type` header is always visible in the request form

### CODE REVIEW

**Comment by esphen** [comment]
Just published the first release candidate, [2.1.0-rc.1](https://github.com/esphen/RESTED/releases/tag/2.1.0-rc.1). I added compiled extension files there, please test!

cc @moderndeveloperllc

**Comment by moderndeveloperllc** [comment]
@esphen Switching Request Body Type to Custom gives me this error:
```
uncaught at r 
 at v 
 at i 
 at g 
 Error: Body type custom is not supported
    at chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:509985
    at o (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:18787)
    at Generator._invoke (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:20196)
    at Generator.e.(anonymous function) [as next] (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:29:18966)
    at b (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:26:11564)
    at n (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:26:12305)
    at I (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:26:15554)
    at E (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:26:13149)
    at b (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:26:11624)
    at l (chrome-extension://efhficcaphambolcidkajacbepebblnj/dist/rested.js:26:17001)
```
FWIW, I was able to use the JSON type well. Perhaps using that as a Body Type would also set the `Content-Type` header to `application/json` if a different one wasn't already set? Just a thought.

**Comment by moderndeveloperllc** [comment]
I also see (in Opera) the extension still having a 2.0.4 version number. Not sure if that will change when you release, or if that's an oversight.

**Comment by esphen** [comment]
> Switching Request Body Type to Custom (Method - POST) gives me this error

Thanks! I'll fix that

> FWIW, I was able to use the JSON type well. Perhaps using that as a Body Type would also set the Content-Type header to application/json if a different one wasn't already set? Just a thought.

It should already do that. If it doesn't, that's a bug. I can reproduce this when I go to the custom type and back. I'll fix this too.

> I also see (in Opera) the extension still having a 2.0.4 version number. Not sure if that will change when you release, or if that's an oversight.

Yeah, I saw that right after I published the rc. It's an oversight I'll fix in the next release, but it shouldn't matter that much.

Thanks for helping test, it is very much appreciated!

**Comment by moderndeveloperllc** [comment]
Getting all the Response headers back looks to be working great. I'm noticing the Content-Type issue with POSTs it seems.

**Comment by esphen** [comment]
[2.1.0 RC 3](https://github.com/esphen/RESTED/releases/tag/2.1.0-rc.3) is out!

@moderndeveloperllc Does it look better now? Could you also please test a redirect request (like https://httpbin.org/redirect/6) and an https redirect (like http://news.ycombinator.com) and see if they are visible above the response?

**Comment by moderndeveloperllc** [comment]
@esphen The redirects are working great for me. Will the collections transfer over if I update in place? Installing them side by side the 2.1 extension doesn't have the 18 or so I've created.

**Comment by esphen** [comment]
> Will the collections transfer over if I update in place?

Yes, there is no reason why they shouldn't. Have a look in the URL - if the URL is different in 2.1 than in 2.x, then that is why there is no collections there. When updating, the ID will not change, but I guess there is no guarantee that it will stay the same when you install manually.

**Comment by esphen** [comment]
Published and awaiting review

**Pull request merged**
